package atua.anddev.globaltv.database.greendao;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

import atua.anddev.globaltv.entity.Channel;
import atua.anddev.globaltv.entity.ChannelGuide;
import atua.anddev.globaltv.entity.Favorite;
import atua.anddev.globaltv.entity.GuideProv;
import atua.anddev.globaltv.entity.Logo;
import atua.anddev.globaltv.entity.Playlist;
import atua.anddev.globaltv.entity.Programme;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig channelDaoConfig;
    private final DaoConfig channelGuideDaoConfig;
    private final DaoConfig guideProvDaoConfig;
    private final DaoConfig logoDaoConfig;
    private final DaoConfig playlistDaoConfig;
    private final DaoConfig programmeDaoConfig;
    private final DaoConfig favoriteDaoConfig;

    private final ChannelDao channelDao;
    private final ChannelGuideDao channelGuideDao;
    private final GuideProvDao guideProvDao;
    private final LogoDao logoDao;
    private final PlaylistDao playlistDao;
    private final ProgrammeDao programmeDao;
    private final FavoriteDao favoriteDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        channelDaoConfig = daoConfigMap.get(ChannelDao.class).clone();
        channelDaoConfig.initIdentityScope(type);

        channelGuideDaoConfig = daoConfigMap.get(ChannelGuideDao.class).clone();
        channelGuideDaoConfig.initIdentityScope(type);

        guideProvDaoConfig = daoConfigMap.get(GuideProvDao.class).clone();
        guideProvDaoConfig.initIdentityScope(type);

        logoDaoConfig = daoConfigMap.get(LogoDao.class).clone();
        logoDaoConfig.initIdentityScope(type);

        playlistDaoConfig = daoConfigMap.get(PlaylistDao.class).clone();
        playlistDaoConfig.initIdentityScope(type);

        programmeDaoConfig = daoConfigMap.get(ProgrammeDao.class).clone();
        programmeDaoConfig.initIdentityScope(type);

        favoriteDaoConfig = daoConfigMap.get(FavoriteDao.class).clone();
        favoriteDaoConfig.initIdentityScope(type);

        channelDao = new ChannelDao(channelDaoConfig, this);
        channelGuideDao = new ChannelGuideDao(channelGuideDaoConfig, this);
        guideProvDao = new GuideProvDao(guideProvDaoConfig, this);
        logoDao = new LogoDao(logoDaoConfig, this);
        playlistDao = new PlaylistDao(playlistDaoConfig, this);
        programmeDao = new ProgrammeDao(programmeDaoConfig, this);
        favoriteDao = new FavoriteDao(favoriteDaoConfig, this);

        registerDao(Channel.class, channelDao);
        registerDao(ChannelGuide.class, channelGuideDao);
        registerDao(GuideProv.class, guideProvDao);
        registerDao(Logo.class, logoDao);
        registerDao(Playlist.class, playlistDao);
        registerDao(Programme.class, programmeDao);
        registerDao(Favorite.class, favoriteDao);
    }

    public void clear() {
        channelDaoConfig.clearIdentityScope();
        channelGuideDaoConfig.clearIdentityScope();
        guideProvDaoConfig.clearIdentityScope();
        logoDaoConfig.clearIdentityScope();
        playlistDaoConfig.clearIdentityScope();
        programmeDaoConfig.clearIdentityScope();
        favoriteDaoConfig.clearIdentityScope();
    }

    public ChannelDao getChannelDao() {
        return channelDao;
    }

    public ChannelGuideDao getChannelGuideDao() {
        return channelGuideDao;
    }

    public GuideProvDao getGuideProvDao() {
        return guideProvDao;
    }

    public LogoDao getLogoDao() {
        return logoDao;
    }

    public PlaylistDao getPlaylistDao() {
        return playlistDao;
    }

    public ProgrammeDao getProgrammeDao() {
        return programmeDao;
    }

    public FavoriteDao getFavoriteDao() {
        return favoriteDao;
    }

}
